---
- name: be sure IUS repo installed
  yum:
    name: https://centos7.iuscommunity.org/ius-release.rpm

- name: Install Common PHP-Packages
  become: yes
  yum:
    name:
      - php71u-fpm
      - php71u-common
      - php71u-devel
      - php71u-cli
      - php71u-pdo
      - php71u-gd
      - php71u-xml
      - php71u-mbstring
      - php71u-mcrypt
      - php71u-mysqlnd
      - php71u-igbinary
      - php71u-bcmath
      - php71u-opcache

- name: disable pool www.conf
  become: yes
  command: mv /etc/php-fpm.d/www.conf /etc/php-fpm.d/www.conf.dead
  
- name: Copy php.ini
  become: yes
  template:
    src: php.ini.j2
    dest: /etc/php.ini

- name: Copy new pool php-fpm
  become: yes
  template: src=hokage.conf.j2 dest=/etc/php-fpm.d/hokage.conf

- name: Automatic load on boot
  become: yes
  command: systemctl enable php-fpm.service

- name: Be sure php-fpm is running and enable
  become: yes
  systemd: name=php-fpm state=reloaded enabled=yes