---
- name: Install epel repo
  become: yes
  yum:
    name: epel-release
    state: present
  notify:
    - update repo
    
- name: Be sure common packages is installed
  become: yes
  yum: 
    name:
      - vim
      - wget
      - curl
      - git
      - htop
      - net-tools
      - mlocate
      - policycoreutils-python
    state: present

- name: upgrade all packages
  become: yes
  yum:
    name: '*'
    state: latest