---
- name: Be sure common packages is installed
  become: yes
  yum: 
    name:
      - epel-release
      - vim
      - wget
      - curl
      - git
      - htop
      - net-tools
      - mlocate
      - policycoreutils-python
    state: present
